/**
 * Seed script for pre-loading standard security controls
 * Includes ISO 27001:2022 Annex A controls (93 total) and SOC 2 Trust Service Criteria
 * 
 * Run with: npx tsx scripts/seed-security-controls.ts
 */

import { db } from "../lib/db"
import { securityStandardControls, securityStandardClauses } from "../lib/db/schema/security"

// ============================================================================
// ISO 27001:2022 ANNEX A CONTROLS
// ============================================================================

const iso27001Controls = [
  // A.5 - Organizational Controls (37 controls)
  { controlId: "A.5.1", category: "Organizational", subcategory: "Policies for information security", title: "Policies for information security", description: "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur." },
  { controlId: "A.5.2", category: "Organizational", subcategory: "Policies for information security", title: "Information security roles and responsibilities", description: "Information security roles and responsibilities shall be defined and allocated according to the organization needs." },
  { controlId: "A.5.3", category: "Organizational", subcategory: "Policies for information security", title: "Segregation of duties", description: "Conflicting duties and conflicting areas of responsibility shall be segregated." },
  { controlId: "A.5.4", category: "Organizational", subcategory: "Policies for information security", title: "Management responsibilities", description: "Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization." },
  { controlId: "A.5.5", category: "Organizational", subcategory: "Policies for information security", title: "Contact with authorities", description: "The organization shall establish and maintain contact with relevant authorities." },
  { controlId: "A.5.6", category: "Organizational", subcategory: "Policies for information security", title: "Contact with special interest groups", description: "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations." },
  { controlId: "A.5.7", category: "Organizational", subcategory: "Threat intelligence", title: "Threat intelligence", description: "Information relating to information security threats shall be collected and analysed to produce threat intelligence." },
  { controlId: "A.5.8", category: "Organizational", subcategory: "Information security in project management", title: "Information security in project management", description: "Information security shall be integrated into project management." },
  { controlId: "A.5.9", category: "Organizational", subcategory: "Inventory of information and other associated assets", title: "Inventory of information and other associated assets", description: "An inventory of information and other associated assets, including owners, shall be developed and maintained." },
  { controlId: "A.5.10", category: "Organizational", subcategory: "Inventory of information and other associated assets", title: "Acceptable use of information and other associated assets", description: "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented." },
  { controlId: "A.5.11", category: "Organizational", subcategory: "Inventory of information and other associated assets", title: "Return of assets", description: "Personnel and other interested parties as appropriate shall return all the organization's assets in their possession upon change or termination of their employment, contract or agreement." },
  { controlId: "A.5.12", category: "Organizational", subcategory: "Classification of information", title: "Classification of information", description: "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements." },
  { controlId: "A.5.13", category: "Organizational", subcategory: "Classification of information", title: "Labelling of information", description: "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization." },
  { controlId: "A.5.14", category: "Organizational", subcategory: "Information transfer", title: "Information transfer", description: "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties." },
  { controlId: "A.5.15", category: "Organizational", subcategory: "Access control", title: "Access control", description: "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements." },
  { controlId: "A.5.16", category: "Organizational", subcategory: "Identity management", title: "Identity management", description: "The full life cycle of identities shall be managed." },
  { controlId: "A.5.17", category: "Organizational", subcategory: "Identity management", title: "Authentication information", description: "Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information." },
  { controlId: "A.5.18", category: "Organizational", subcategory: "Access rights", title: "Access rights", description: "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization's topic-specific policy on and rules for access control." },
  { controlId: "A.5.19", category: "Organizational", subcategory: "Information security in supplier relationships", title: "Information security in supplier relationships", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services." },
  { controlId: "A.5.20", category: "Organizational", subcategory: "Information security in supplier relationships", title: "Addressing information security within supplier agreements", description: "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship." },
  { controlId: "A.5.21", category: "Organizational", subcategory: "Information security in supplier relationships", title: "Managing information security in the ICT supply chain", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain." },
  { controlId: "A.5.22", category: "Organizational", subcategory: "Information security in supplier relationships", title: "Monitoring, review and change management of supplier services", description: "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery." },
  { controlId: "A.5.23", category: "Organizational", subcategory: "Information security for use of cloud services", title: "Information security for use of cloud services", description: "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements." },
  { controlId: "A.5.24", category: "Organizational", subcategory: "Information security incident management", title: "Information security incident management planning and preparation", description: "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities." },
  { controlId: "A.5.25", category: "Organizational", subcategory: "Information security incident management", title: "Assessment and decision on information security events", description: "The organization shall assess information security events and decide if they are to be categorized as information security incidents." },
  { controlId: "A.5.26", category: "Organizational", subcategory: "Information security incident management", title: "Response to information security incidents", description: "Information security incidents shall be responded to in accordance with the documented procedures." },
  { controlId: "A.5.27", category: "Organizational", subcategory: "Information security incident management", title: "Learning from information security incidents", description: "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls." },
  { controlId: "A.5.28", category: "Organizational", subcategory: "Information security incident management", title: "Collection of evidence", description: "The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events." },
  { controlId: "A.5.29", category: "Organizational", subcategory: "Business continuity", title: "Information security during disruption", description: "The organization shall plan how to maintain information security at an appropriate level during disruption." },
  { controlId: "A.5.30", category: "Organizational", subcategory: "Business continuity", title: "ICT readiness for business continuity", description: "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements." },
  { controlId: "A.5.31", category: "Organizational", subcategory: "Compliance", title: "Legal, statutory, regulatory and contractual requirements", description: "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date." },
  { controlId: "A.5.32", category: "Organizational", subcategory: "Compliance", title: "Intellectual property rights", description: "The organization shall implement appropriate procedures to protect intellectual property rights." },
  { controlId: "A.5.33", category: "Organizational", subcategory: "Compliance", title: "Protection of records", description: "Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release." },
  { controlId: "A.5.34", category: "Organizational", subcategory: "Compliance", title: "Privacy and protection of PII", description: "The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements." },
  { controlId: "A.5.35", category: "Organizational", subcategory: "Compliance", title: "Independent review of information security", description: "The organization's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur." },
  { controlId: "A.5.36", category: "Organizational", subcategory: "Compliance", title: "Compliance with policies, rules and standards for information security", description: "Compliance with the organization's information security policy, topic-specific policies, rules and standards shall be regularly reviewed." },
  { controlId: "A.5.37", category: "Organizational", subcategory: "Compliance", title: "Documented operating procedures", description: "Operating procedures for information processing facilities shall be documented and made available to personnel who need them." },
  
  // A.6 - People Controls (8 controls)
  { controlId: "A.6.1", category: "People", subcategory: "Screening", title: "Screening", description: "Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks." },
  { controlId: "A.6.2", category: "People", subcategory: "Terms and conditions of employment", title: "Terms and conditions of employment", description: "The employment contractual agreements shall state the personnel's and the organization's responsibilities for information security." },
  { controlId: "A.6.3", category: "People", subcategory: "Information security awareness, education and training", title: "Information security awareness, education and training", description: "Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function." },
  { controlId: "A.6.4", category: "People", subcategory: "Disciplinary process", title: "Disciplinary process", description: "A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation." },
  { controlId: "A.6.5", category: "People", subcategory: "Responsibilities after termination or change of employment", title: "Responsibilities after termination or change of employment", description: "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties." },
  { controlId: "A.6.6", category: "People", subcategory: "Confidentiality or non-disclosure agreements", title: "Confidentiality or non-disclosure agreements", description: "Confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties." },
  { controlId: "A.6.7", category: "People", subcategory: "Remote working", title: "Remote working", description: "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises." },
  { controlId: "A.6.8", category: "People", subcategory: "Information security event reporting", title: "Information security event reporting", description: "The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner." },
  
  // A.7 - Physical Controls (14 controls)
  { controlId: "A.7.1", category: "Physical", subcategory: "Physical security perimeters", title: "Physical security perimeters", description: "Security perimeters shall be defined and used to protect areas that contain information and other associated assets." },
  { controlId: "A.7.2", category: "Physical", subcategory: "Physical entry", title: "Physical entry", description: "Secure areas shall be protected by appropriate entry controls and access points." },
  { controlId: "A.7.3", category: "Physical", subcategory: "Securing offices, rooms and facilities", title: "Securing offices, rooms and facilities", description: "Physical security for offices, rooms and facilities shall be designed and implemented." },
  { controlId: "A.7.4", category: "Physical", subcategory: "Physical security monitoring", title: "Physical security monitoring", description: "Premises shall be continuously monitored for unauthorized physical access." },
  { controlId: "A.7.5", category: "Physical", subcategory: "Protecting against physical and environmental threats", title: "Protecting against physical and environmental threats", description: "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented." },
  { controlId: "A.7.6", category: "Physical", subcategory: "Working in secure areas", title: "Working in secure areas", description: "Security measures for working in secure areas shall be designed and implemented." },
  { controlId: "A.7.7", category: "Physical", subcategory: "Clear desk and clear screen", title: "Clear desk and clear screen", description: "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced." },
  { controlId: "A.7.8", category: "Physical", subcategory: "Equipment siting and protection", title: "Equipment siting and protection", description: "Equipment shall be sited securely and protected." },
  { controlId: "A.7.9", category: "Physical", subcategory: "Security of assets off-premises", title: "Security of assets off-premises", description: "Off-site assets shall be protected." },
  { controlId: "A.7.10", category: "Physical", subcategory: "Storage media", title: "Storage media", description: "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization's classification scheme and handling requirements." },
  { controlId: "A.7.11", category: "Physical", subcategory: "Supporting utilities", title: "Supporting utilities", description: "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities." },
  { controlId: "A.7.12", category: "Physical", subcategory: "Cabling security", title: "Cabling security", description: "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage." },
  { controlId: "A.7.13", category: "Physical", subcategory: "Equipment maintenance", title: "Equipment maintenance", description: "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information." },
  { controlId: "A.7.14", category: "Physical", subcategory: "Secure disposal or re-use of equipment", title: "Secure disposal or re-use of equipment", description: "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use." },
  
  // A.8 - Technological Controls (34 controls)
  { controlId: "A.8.1", category: "Technological", subcategory: "User endpoint devices", title: "User endpoint devices", description: "Information stored on, processed by or accessible via user endpoint devices shall be protected." },
  { controlId: "A.8.2", category: "Technological", subcategory: "Privileged access rights", title: "Privileged access rights", description: "The allocation and use of privileged access rights shall be restricted and managed." },
  { controlId: "A.8.3", category: "Technological", subcategory: "Information access restriction", title: "Information access restriction", description: "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control." },
  { controlId: "A.8.4", category: "Technological", subcategory: "Access to source code", title: "Access to source code", description: "Read and write access to source code, development tools and software libraries shall be appropriately managed." },
  { controlId: "A.8.5", category: "Technological", subcategory: "Secure authentication", title: "Secure authentication", description: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control." },
  { controlId: "A.8.6", category: "Technological", subcategory: "Capacity management", title: "Capacity management", description: "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements." },
  { controlId: "A.8.7", category: "Technological", subcategory: "Protection against malware", title: "Protection against malware", description: "Protection against malware shall be implemented and supported by appropriate user awareness." },
  { controlId: "A.8.8", category: "Technological", subcategory: "Management of technical vulnerabilities", title: "Management of technical vulnerabilities", description: "Information about technical vulnerabilities of information systems in use shall be obtained, the organization's exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken." },
  { controlId: "A.8.9", category: "Technological", subcategory: "Configuration management", title: "Configuration management", description: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed." },
  { controlId: "A.8.10", category: "Technological", subcategory: "Information deletion", title: "Information deletion", description: "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required." },
  { controlId: "A.8.11", category: "Technological", subcategory: "Data masking", title: "Data masking", description: "Data masking shall be used in accordance with the organization's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration." },
  { controlId: "A.8.12", category: "Technological", subcategory: "Data leakage prevention", title: "Data leakage prevention", description: "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information." },
  { controlId: "A.8.13", category: "Technological", subcategory: "Information backup", title: "Information backup", description: "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup." },
  { controlId: "A.8.14", category: "Technological", subcategory: "Redundancy of information processing facilities", title: "Redundancy of information processing facilities", description: "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements." },
  { controlId: "A.8.15", category: "Technological", subcategory: "Logging", title: "Logging", description: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed." },
  { controlId: "A.8.16", category: "Technological", subcategory: "Monitoring activities", title: "Monitoring activities", description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents." },
  { controlId: "A.8.17", category: "Technological", subcategory: "Clock synchronization", title: "Clock synchronization", description: "The clocks of information processing systems used by the organization shall be synchronized to approved time sources." },
  { controlId: "A.8.18", category: "Technological", subcategory: "Use of privileged utility programs", title: "Use of privileged utility programs", description: "The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled." },
  { controlId: "A.8.19", category: "Technological", subcategory: "Installation of software on operational systems", title: "Installation of software on operational systems", description: "Procedures and measures shall be implemented to securely manage software installation on operational systems." },
  { controlId: "A.8.20", category: "Technological", subcategory: "Networks security", title: "Networks security", description: "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications." },
  { controlId: "A.8.21", category: "Technological", subcategory: "Security of network services", title: "Security of network services", description: "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored." },
  { controlId: "A.8.22", category: "Technological", subcategory: "Segregation of networks", title: "Segregation of networks", description: "Groups of information services, users and information systems shall be segregated in the organization's networks." },
  { controlId: "A.8.23", category: "Technological", subcategory: "Web filtering", title: "Web filtering", description: "Access to external websites shall be managed to reduce exposure to malicious content." },
  { controlId: "A.8.24", category: "Technological", subcategory: "Use of cryptography", title: "Use of cryptography", description: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented." },
  { controlId: "A.8.25", category: "Technological", subcategory: "Secure development life cycle", title: "Secure development life cycle", description: "Rules for the secure development of software and systems shall be established and applied." },
  { controlId: "A.8.26", category: "Technological", subcategory: "Application security requirements", title: "Application security requirements", description: "Information security requirements shall be identified, specified and approved when developing or acquiring applications." },
  { controlId: "A.8.27", category: "Technological", subcategory: "Secure system architecture and engineering principles", title: "Secure system architecture and engineering principles", description: "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities." },
  { controlId: "A.8.28", category: "Technological", subcategory: "Secure coding", title: "Secure coding", description: "Secure coding principles shall be applied to software development." },
  { controlId: "A.8.29", category: "Technological", subcategory: "Security testing in development and acceptance", title: "Security testing in development and acceptance", description: "Security testing processes shall be defined and implemented in the development life cycle." },
  { controlId: "A.8.30", category: "Technological", subcategory: "Outsourced development", title: "Outsourced development", description: "The organization shall direct, monitor and review the activities related to outsourced system development." },
  { controlId: "A.8.31", category: "Technological", subcategory: "Separation of development, test and production environments", title: "Separation of development, test and production environments", description: "Development, testing and production environments shall be separated and secured." },
  { controlId: "A.8.32", category: "Technological", subcategory: "Change management", title: "Change management", description: "Changes to information processing facilities and information systems shall be subject to change management procedures." },
  { controlId: "A.8.33", category: "Technological", subcategory: "Test information", title: "Test information", description: "Test information shall be appropriately selected, protected and managed." },
  { controlId: "A.8.34", category: "Technological", subcategory: "Protection of information systems during audit testing", title: "Protection of information systems during audit testing", description: "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management." },
]

// ============================================================================
// SOC 2 TRUST SERVICE CRITERIA
// ============================================================================

const soc2Controls = [
  // CC1 - Control Environment
  { controlId: "CC1.1", category: "Security - Control Environment", subcategory: "COSO Principle 1", title: "Demonstrates commitment to integrity and ethical values", description: "The entity demonstrates a commitment to integrity and ethical values." },
  { controlId: "CC1.2", category: "Security - Control Environment", subcategory: "COSO Principle 2", title: "Exercises oversight responsibility", description: "The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control." },
  { controlId: "CC1.3", category: "Security - Control Environment", subcategory: "COSO Principle 3", title: "Establishes structure, authority, and responsibility", description: "Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives." },
  { controlId: "CC1.4", category: "Security - Control Environment", subcategory: "COSO Principle 4", title: "Demonstrates commitment to competence", description: "The entity demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives." },
  { controlId: "CC1.5", category: "Security - Control Environment", subcategory: "COSO Principle 5", title: "Enforces accountability", description: "The entity holds individuals accountable for their internal control responsibilities in the pursuit of objectives." },
  
  // CC2 - Communication and Information
  { controlId: "CC2.1", category: "Security - Communication and Information", subcategory: "COSO Principle 13", title: "Obtains or generates relevant, quality information", description: "The entity obtains or generates and uses relevant, quality information to support the functioning of internal control." },
  { controlId: "CC2.2", category: "Security - Communication and Information", subcategory: "COSO Principle 14", title: "Communicates internally", description: "The entity internally communicates information, including objectives and responsibilities for internal control, necessary to support the functioning of internal control." },
  { controlId: "CC2.3", category: "Security - Communication and Information", subcategory: "COSO Principle 15", title: "Communicates externally", description: "The entity communicates with external parties regarding matters affecting the functioning of internal control." },
  
  // CC3 - Risk Assessment
  { controlId: "CC3.1", category: "Security - Risk Assessment", subcategory: "COSO Principle 6", title: "Specifies suitable objectives", description: "The entity specifies objectives with sufficient clarity to enable the identification and assessment of risks relating to objectives." },
  { controlId: "CC3.2", category: "Security - Risk Assessment", subcategory: "COSO Principle 7", title: "Identifies and analyzes risk", description: "The entity identifies risks to the achievement of its objectives across the entity and analyzes risks as a basis for determining how the risks should be managed." },
  { controlId: "CC3.3", category: "Security - Risk Assessment", subcategory: "COSO Principle 8", title: "Considers potential for fraud", description: "The entity considers the potential for fraud in assessing risks to the achievement of objectives." },
  { controlId: "CC3.4", category: "Security - Risk Assessment", subcategory: "COSO Principle 9", title: "Identifies and analyzes significant change", description: "The entity identifies and assesses changes that could significantly impact the system of internal control." },
  
  // CC4 - Monitoring Activities
  { controlId: "CC4.1", category: "Security - Monitoring Activities", subcategory: "COSO Principle 16", title: "Selects and develops ongoing and/or separate evaluations", description: "The entity selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning." },
  { controlId: "CC4.2", category: "Security - Monitoring Activities", subcategory: "COSO Principle 17", title: "Evaluates and communicates deficiencies", description: "The entity evaluates and communicates internal control deficiencies in a timely manner to those parties responsible for taking corrective action, including senior management and the board of directors, as appropriate." },
  
  // CC5 - Control Activities
  { controlId: "CC5.1", category: "Security - Control Activities", subcategory: "COSO Principle 10", title: "Selects and develops control activities", description: "The entity selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives to acceptable levels." },
  { controlId: "CC5.2", category: "Security - Control Activities", subcategory: "COSO Principle 11", title: "Selects and develops general controls over technology", description: "The entity also selects and develops general control activities over technology to support the achievement of objectives." },
  { controlId: "CC5.3", category: "Security - Control Activities", subcategory: "COSO Principle 12", title: "Deploys through policies and procedures", description: "The entity deploys control activities through policies that establish what is expected and in procedures that put policies into action." },
  
  // CC6 - Logical and Physical Access Controls
  { controlId: "CC6.1", category: "Security - Logical and Physical Access", subcategory: "Logical Access", title: "Security software, infrastructure, and architectures", description: "The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events." },
  { controlId: "CC6.2", category: "Security - Logical and Physical Access", subcategory: "Logical Access", title: "Authentication and access", description: "Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users whose access is administered by the entity." },
  { controlId: "CC6.3", category: "Security - Logical and Physical Access", subcategory: "Logical Access", title: "Access removal", description: "The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets based on roles, responsibilities, or the system design and changes." },
  { controlId: "CC6.4", category: "Security - Logical and Physical Access", subcategory: "Physical Access", title: "Physical access restrictions", description: "The entity restricts physical access to facilities and protected information assets to authorized personnel." },
  { controlId: "CC6.5", category: "Security - Logical and Physical Access", subcategory: "Physical Access", title: "Physical access to assets", description: "The entity discontinues logical and physical protections over physical assets only after the ability to read or recover data and software from those assets has been diminished." },
  { controlId: "CC6.6", category: "Security - Logical and Physical Access", subcategory: "External Threats", title: "Security events against threats", description: "The entity implements logical access security measures to protect against threats from sources outside its system boundaries." },
  { controlId: "CC6.7", category: "Security - Logical and Physical Access", subcategory: "Data Transmission", title: "Information transmission", description: "The entity restricts the transmission, movement, and removal of information to authorized internal and external users and processes, and protects it during transmission." },
  { controlId: "CC6.8", category: "Security - Logical and Physical Access", subcategory: "Malware", title: "Malicious software prevention", description: "The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software." },
  
  // CC7 - System Operations
  { controlId: "CC7.1", category: "Security - System Operations", subcategory: "Detection", title: "Vulnerability detection", description: "To meet its objectives, the entity uses detection and monitoring procedures to identify changes to configurations that result in the introduction of new vulnerabilities, and susceptibilities to newly discovered vulnerabilities." },
  { controlId: "CC7.2", category: "Security - System Operations", subcategory: "Incident Response", title: "Security incident monitoring", description: "The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors affecting the entity's ability to meet its objectives." },
  { controlId: "CC7.3", category: "Security - System Operations", subcategory: "Incident Response", title: "Security incident evaluation", description: "The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives and, if so, takes actions to prevent or address such failures." },
  { controlId: "CC7.4", category: "Security - System Operations", subcategory: "Incident Response", title: "Security incident response", description: "The entity responds to identified security incidents by executing a defined incident response program to understand, contain, remediate, and communicate security incidents." },
  { controlId: "CC7.5", category: "Security - System Operations", subcategory: "Recovery", title: "Recovery from incidents", description: "The entity identifies, develops, and implements activities to recover from identified security incidents." },
  
  // CC8 - Change Management
  { controlId: "CC8.1", category: "Security - Change Management", subcategory: "Change Management", title: "Infrastructure and software changes", description: "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures to meet its objectives." },
  
  // CC9 - Risk Mitigation
  { controlId: "CC9.1", category: "Security - Risk Mitigation", subcategory: "Risk Mitigation", title: "Vendor risk management", description: "The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions." },
  { controlId: "CC9.2", category: "Security - Risk Mitigation", subcategory: "Risk Mitigation", title: "Business continuity", description: "The entity assesses and manages risks associated with vendors and business partners." },
  
  // A1 - Availability
  { controlId: "A1.1", category: "Availability", subcategory: "System Availability", title: "System availability management", description: "The entity maintains, monitors, and evaluates current processing capacity and use of system components to manage capacity demand and to enable the implementation of additional capacity." },
  { controlId: "A1.2", category: "Availability", subcategory: "Recovery", title: "Environmental and data recovery", description: "The entity authorizes, designs, develops or acquires, implements, operates, approves, maintains, and monitors environmental protections, software, data backup processes, and recovery infrastructure." },
  { controlId: "A1.3", category: "Availability", subcategory: "Business Continuity", title: "Business continuity testing", description: "The entity tests recovery plan procedures supporting system recovery to meet its objectives." },
  
  // PI1 - Processing Integrity
  { controlId: "PI1.1", category: "Processing Integrity", subcategory: "Data Processing", title: "Processing accuracy and completeness", description: "The entity implements policies and procedures over system processing to result in products, services, and reporting to meet the entity's objectives." },
  { controlId: "PI1.2", category: "Processing Integrity", subcategory: "Data Processing", title: "Input validation", description: "The entity implements policies and procedures over system inputs to result in products, services, and reporting to meet the entity's objectives." },
  { controlId: "PI1.3", category: "Processing Integrity", subcategory: "Data Processing", title: "Processing error handling", description: "The entity implements policies and procedures over system processing to result in products, services, and reporting to meet the entity's objectives." },
  { controlId: "PI1.4", category: "Processing Integrity", subcategory: "Output", title: "Output completeness and accuracy", description: "The entity implements policies and procedures to make available or deliver output completely, accurately, and timely in accordance with specifications to meet the entity's objectives." },
  { controlId: "PI1.5", category: "Processing Integrity", subcategory: "Data Retention", title: "Data storage and retention", description: "The entity implements policies and procedures to store inputs, items in processing, and outputs completely, accurately, and timely in accordance with system specifications." },
  
  // C1 - Confidentiality
  { controlId: "C1.1", category: "Confidentiality", subcategory: "Confidential Information", title: "Confidential information identification", description: "The entity identifies and maintains confidential information to meet the entity's objectives related to confidentiality." },
  { controlId: "C1.2", category: "Confidentiality", subcategory: "Confidential Information", title: "Confidential information disposal", description: "The entity disposes of confidential information to meet the entity's objectives related to confidentiality." },
  
  // P1-P8 - Privacy
  { controlId: "P1.1", category: "Privacy", subcategory: "Notice", title: "Privacy notice", description: "The entity provides notice to data subjects about its privacy practices." },
  { controlId: "P2.1", category: "Privacy", subcategory: "Choice and Consent", title: "Privacy choice and consent", description: "The entity communicates choices available regarding the collection, use, retention, disclosure, and disposal of personal information to data subjects." },
  { controlId: "P3.1", category: "Privacy", subcategory: "Collection", title: "Personal information collection", description: "Personal information is collected consistent with the entity's objectives related to privacy." },
  { controlId: "P3.2", category: "Privacy", subcategory: "Collection", title: "Explicit consent for sensitive information", description: "For information requiring explicit consent, the entity communicates the need for such consent." },
  { controlId: "P4.1", category: "Privacy", subcategory: "Use, Retention, and Disposal", title: "Personal information use limitation", description: "The entity limits the use of personal information to the purposes identified in the entity's objectives." },
  { controlId: "P4.2", category: "Privacy", subcategory: "Use, Retention, and Disposal", title: "Personal information retention", description: "The entity retains personal information consistent with the entity's objectives related to privacy." },
  { controlId: "P4.3", category: "Privacy", subcategory: "Use, Retention, and Disposal", title: "Personal information disposal", description: "The entity securely disposes of personal information to meet the entity's objectives related to privacy." },
  { controlId: "P5.1", category: "Privacy", subcategory: "Access", title: "Personal information access", description: "The entity grants identified and authenticated data subjects the ability to access their stored personal information for review." },
  { controlId: "P5.2", category: "Privacy", subcategory: "Access", title: "Personal information correction", description: "The entity corrects, amends, or appends personal information based on information provided by data subjects." },
  { controlId: "P6.1", category: "Privacy", subcategory: "Disclosure and Notification", title: "Personal information disclosure", description: "The entity discloses personal information to third parties with the consent of the data subjects." },
  { controlId: "P6.2", category: "Privacy", subcategory: "Disclosure and Notification", title: "Third party privacy practices", description: "The entity creates and retains a complete, accurate, and timely record of authorized disclosures of personal information." },
  { controlId: "P6.3", category: "Privacy", subcategory: "Disclosure and Notification", title: "Notification of third party access", description: "The entity notifies affected data subjects, regulators, and others when a breach or suspected breach of privacy occurs." },
  { controlId: "P6.4", category: "Privacy", subcategory: "Disclosure and Notification", title: "Privacy breach notification", description: "The entity provides data subjects with an accounting of the personal information held." },
  { controlId: "P6.5", category: "Privacy", subcategory: "Disclosure and Notification", title: "Accounting of disclosures", description: "The entity creates and retains a complete, accurate, and timely record of detected or reported unauthorized access." },
  { controlId: "P6.6", category: "Privacy", subcategory: "Disclosure and Notification", title: "Privacy rights notification", description: "The entity notifies data subjects if the entity makes material changes to the entity's privacy notice." },
  { controlId: "P6.7", category: "Privacy", subcategory: "Disclosure and Notification", title: "Unauthorized access notification", description: "The entity provides a means for data subjects to communicate regarding privacy issues or complaints." },
  { controlId: "P7.1", category: "Privacy", subcategory: "Quality", title: "Personal information accuracy", description: "The entity collects and maintains accurate, up-to-date, complete, and relevant personal information necessary to meet the entity's objectives." },
  { controlId: "P8.1", category: "Privacy", subcategory: "Monitoring and Enforcement", title: "Privacy compliance monitoring", description: "The entity implements a process for receiving, addressing, resolving, and communicating the resolution of inquiries, complaints, and disputes from data subjects." },
]

async function seedSecurityControls() {
  console.log("🔐 Seeding security standard controls...")
  
  // ============================================================================
// ISO 27001:2022 ISMS CLAUSES (4-10) - Management System Requirements
// ============================================================================

const iso27001Clauses = [
  // Clause 4 - Context of the Organization
  { clauseId: "4", category: "Context", title: "Context of the Organization", description: "Establishes the context for the ISMS, including internal and external issues, interested parties, scope, and the management system itself.", guidance: "This clause requires understanding the organization's environment and establishing the foundation for the ISMS.", evidenceExamples: "Context analysis documents, stakeholder register, ISMS scope statement" },
  { clauseId: "4.1", category: "Context", parentClauseId: "4", title: "Understanding the organization and its context", description: "The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.", guidance: "Conduct PESTLE analysis, identify business objectives, understand regulatory environment, assess organizational culture and capabilities.", evidenceExamples: "PESTLE analysis, business context document, strategic planning documents, organizational structure charts" },
  { clauseId: "4.2", category: "Context", parentClauseId: "4", title: "Understanding the needs and expectations of interested parties", description: "The organization shall determine the interested parties that are relevant to the information security management system and the requirements of these interested parties relevant to information security.", guidance: "Identify all stakeholders (customers, regulators, employees, suppliers, shareholders) and document their security-related requirements.", evidenceExamples: "Stakeholder register, requirements matrix, customer contracts, regulatory requirements list, SLAs" },
  { clauseId: "4.3", category: "Context", parentClauseId: "4", title: "Determining the scope of the information security management system", description: "The organization shall determine the boundaries and applicability of the information security management system to establish its scope. The scope shall be available as documented information.", guidance: "Define physical, logical, and organizational boundaries. Consider interfaces and dependencies with external parties.", evidenceExamples: "ISMS scope document, network diagrams, data flow diagrams, organizational charts, asset inventory" },
  { clauseId: "4.4", category: "Context", parentClauseId: "4", title: "Information security management system", description: "The organization shall establish, implement, maintain and continually improve an information security management system, in accordance with the requirements of this document.", guidance: "Establish the ISMS framework including processes, documentation, and continual improvement mechanisms.", evidenceExamples: "ISMS manual, process documentation, PDCA evidence, management system procedures" },
  
  // Clause 5 - Leadership
  { clauseId: "5", category: "Leadership", title: "Leadership", description: "Defines the requirements for top management leadership and commitment to the ISMS, including policy and organizational roles.", guidance: "Top management must demonstrate visible commitment and actively participate in the ISMS.", evidenceExamples: "Management commitment statements, meeting minutes, resource allocation records" },
  { clauseId: "5.1", category: "Leadership", parentClauseId: "5", title: "Leadership and commitment", description: "Top management shall demonstrate leadership and commitment with respect to the information security management system.", guidance: "Top management must ensure policy alignment with strategic direction, integration of ISMS into business processes, adequate resources, communication of importance, achieving intended outcomes, directing and supporting people, and promoting continual improvement.", evidenceExamples: "Board meeting minutes, management review records, resource allocation documentation, communication records, performance reports" },
  { clauseId: "5.2", category: "Leadership", parentClauseId: "5", title: "Policy", description: "Top management shall establish an information security policy that is appropriate to the purpose of the organization, includes information security objectives, includes a commitment to satisfy applicable requirements, and includes a commitment to continual improvement.", guidance: "Policy must be documented, communicated within the organization, and available to interested parties as appropriate.", evidenceExamples: "Information security policy document, policy distribution records, acknowledgment records, policy review records" },
  { clauseId: "5.3", category: "Leadership", parentClauseId: "5", title: "Organizational roles, responsibilities and authorities", description: "Top management shall ensure that the responsibilities and authorities for roles relevant to information security are assigned and communicated.", guidance: "Define and document roles for ISMS conformance and performance reporting. Consider CISO, information security committee, asset owners, risk owners.", evidenceExamples: "RACI matrix, job descriptions, organizational charts, appointment letters, committee charters" },
  
  // Clause 6 - Planning
  { clauseId: "6", category: "Planning", title: "Planning", description: "Covers planning for the ISMS including risk assessment, risk treatment, and information security objectives.", guidance: "Systematic planning ensures the ISMS addresses risks and opportunities while achieving defined objectives.", evidenceExamples: "Risk assessment reports, risk treatment plans, objectives and plans documentation" },
  { clauseId: "6.1", category: "Planning", parentClauseId: "6", title: "Actions to address risks and opportunities", description: "When planning for the information security management system, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities.", guidance: "Integrate risk management into ISMS planning. Address both negative risks and positive opportunities.", evidenceExamples: "Risk and opportunity register, action plans, integration evidence with other clauses" },
  { clauseId: "6.1.1", category: "Planning", parentClauseId: "6.1", title: "General", description: "The organization shall plan actions to address risks and opportunities, how to integrate and implement the actions into its ISMS processes, and evaluate the effectiveness of these actions.", guidance: "Document planned actions and track their implementation and effectiveness.", evidenceExamples: "Action plans, implementation records, effectiveness evaluation reports" },
  { clauseId: "6.1.2", category: "Planning", parentClauseId: "6.1", title: "Information security risk assessment", description: "The organization shall define and apply an information security risk assessment process that establishes and maintains risk criteria, ensures repeated assessments produce consistent and comparable results, identifies, analyzes, and evaluates risks.", guidance: "Establish risk assessment methodology including criteria for risk acceptance, likelihood, impact, and risk levels.", evidenceExamples: "Risk assessment methodology document, risk criteria definition, risk assessment reports, risk register" },
  { clauseId: "6.1.3", category: "Planning", parentClauseId: "6.1", title: "Information security risk treatment", description: "The organization shall define and apply an information security risk treatment process to select appropriate risk treatment options, determine all controls necessary, compare controls with Annex A, produce a Statement of Applicability, and formulate a risk treatment plan.", guidance: "Document risk treatment decisions, create SoA, and develop risk treatment plans with owners and timelines.", evidenceExamples: "Risk treatment plan, Statement of Applicability, control selection justification, risk acceptance records" },
  { clauseId: "6.2", category: "Planning", parentClauseId: "6", title: "Information security objectives and planning to achieve them", description: "The organization shall establish information security objectives at relevant functions and levels. Objectives shall be consistent with policy, measurable, take into account requirements and risk assessment results, be monitored, communicated, and updated.", guidance: "Set SMART objectives aligned with policy. Plan what will be done, resources needed, responsible parties, timelines, and evaluation methods.", evidenceExamples: "Security objectives document, objective measurement records, resource plans, responsibility assignments, progress reports" },
  { clauseId: "6.3", category: "Planning", parentClauseId: "6", title: "Planning of changes", description: "When the organization determines the need for changes to the information security management system, the changes shall be carried out in a planned manner.", guidance: "Establish change management process for ISMS changes considering purpose, consequences, integrity, resources, and responsibilities.", evidenceExamples: "Change management procedure, change request records, impact assessments, change implementation records" },
  
  // Clause 7 - Support
  { clauseId: "7", category: "Support", title: "Support", description: "Addresses the resources, competence, awareness, communication, and documented information needed to support the ISMS.", guidance: "Ensure adequate support infrastructure for effective ISMS operation.", evidenceExamples: "Resource allocation records, training records, communication records, document management system" },
  { clauseId: "7.1", category: "Support", parentClauseId: "7", title: "Resources", description: "The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the information security management system.", guidance: "Identify and allocate human resources, infrastructure, technology, and budget for ISMS activities.", evidenceExamples: "Budget allocation records, staffing plans, infrastructure documentation, resource requests and approvals" },
  { clauseId: "7.2", category: "Support", parentClauseId: "7", title: "Competence", description: "The organization shall determine the necessary competence of persons doing work that affects its information security performance, ensure persons are competent on the basis of education, training, or experience, take actions to acquire necessary competence, and retain documented information as evidence.", guidance: "Define competency requirements for security roles, assess current competencies, address gaps through training or hiring.", evidenceExamples: "Competency matrix, job descriptions with security requirements, training records, certifications, performance evaluations" },
  { clauseId: "7.3", category: "Support", parentClauseId: "7", title: "Awareness", description: "Persons doing work under the organization's control shall be aware of the information security policy, their contribution to ISMS effectiveness, the benefits of improved performance, and the implications of not conforming.", guidance: "Implement security awareness programs covering policy, individual responsibilities, and consequences of non-compliance.", evidenceExamples: "Awareness training materials, training attendance records, awareness campaign materials, quiz/test results, acknowledgment forms" },
  { clauseId: "7.4", category: "Support", parentClauseId: "7", title: "Communication", description: "The organization shall determine the need for internal and external communications relevant to the information security management system including what, when, with whom, who, and processes.", guidance: "Establish communication plan for security-related information including incident reporting, policy changes, and stakeholder updates.", evidenceExamples: "Communication plan, communication records, meeting minutes, incident notification records, stakeholder communications" },
  { clauseId: "7.5", category: "Support", parentClauseId: "7", title: "Documented information", description: "The organization's information security management system shall include documented information required by this document and determined by the organization as being necessary for the effectiveness of the ISMS.", guidance: "Establish document management system for creating, updating, and controlling ISMS documentation.", evidenceExamples: "Document control procedure, master document list, version control records, document review records" },
  { clauseId: "7.5.1", category: "Support", parentClauseId: "7.5", title: "General", description: "The ISMS shall include documented information required by the standard and determined necessary by the organization for ISMS effectiveness.", guidance: "Extent of documentation depends on organization size, activities, processes, and personnel competence.", evidenceExamples: "ISMS documentation hierarchy, mandatory documents checklist, document inventory" },
  { clauseId: "7.5.2", category: "Support", parentClauseId: "7.5", title: "Creating and updating", description: "When creating and updating documented information, the organization shall ensure appropriate identification and description, format and media, and review and approval for suitability and adequacy.", guidance: "Standardize document templates, naming conventions, version control, and approval processes.", evidenceExamples: "Document templates, naming convention guide, approval workflow records, version history logs" },
  { clauseId: "7.5.3", category: "Support", parentClauseId: "7.5", title: "Control of documented information", description: "Documented information shall be controlled to ensure it is available, suitable for use, and adequately protected. Control activities include distribution, access, retrieval, use, storage, preservation, change control, retention, and disposition.", guidance: "Implement controls for document access, storage, backup, retention, and disposal. Address both internal and external origin documents.", evidenceExamples: "Access control records, backup records, retention schedule, disposal records, external document register" },
  
  // Clause 8 - Operation
  { clauseId: "8", category: "Operation", title: "Operation", description: "Covers the operational planning and control, risk assessment execution, and risk treatment implementation.", guidance: "Execute the plans developed in Clause 6 and manage day-to-day ISMS operations.", evidenceExamples: "Operational procedures, risk assessment results, treatment implementation records" },
  { clauseId: "8.1", category: "Operation", parentClauseId: "8", title: "Operational planning and control", description: "The organization shall plan, implement and control the processes needed to meet information security requirements, and to implement the actions determined in Clause 6. Control of planned changes and review of consequences of unintended changes shall be performed.", guidance: "Establish operational procedures, manage changes, control outsourced processes.", evidenceExamples: "Operational procedures, process documentation, change records, outsourced process controls, corrective action records" },
  { clauseId: "8.2", category: "Operation", parentClauseId: "8", title: "Information security risk assessment", description: "The organization shall perform information security risk assessments at planned intervals or when significant changes are proposed or occur, taking account of the criteria established in 6.1.2.", guidance: "Conduct regular risk assessments (typically annually) and when significant changes occur. Retain documented results.", evidenceExamples: "Risk assessment schedule, risk assessment reports, risk register updates, change-triggered assessment records" },
  { clauseId: "8.3", category: "Operation", parentClauseId: "8", title: "Information security risk treatment", description: "The organization shall implement the information security risk treatment plan. Documented information of the results of the information security risk treatment shall be retained.", guidance: "Execute risk treatment plans, track implementation progress, document results and residual risks.", evidenceExamples: "Risk treatment implementation records, control implementation evidence, residual risk documentation, treatment effectiveness reports" },
  
  // Clause 9 - Performance Evaluation
  { clauseId: "9", category: "Performance Evaluation", title: "Performance Evaluation", description: "Addresses monitoring, measurement, analysis, evaluation, internal audit, and management review of the ISMS.", guidance: "Establish mechanisms to evaluate ISMS performance and drive continual improvement.", evidenceExamples: "Performance metrics, audit reports, management review minutes" },
  { clauseId: "9.1", category: "Performance Evaluation", parentClauseId: "9", title: "Monitoring, measurement, analysis and evaluation", description: "The organization shall determine what needs to be monitored and measured, methods for monitoring, measurement, analysis and evaluation, when monitoring and measuring shall be performed, who shall monitor and measure, when results shall be analyzed and evaluated, and who shall analyze and evaluate.", guidance: "Define KPIs and metrics for security performance. Establish monitoring processes and responsibilities.", evidenceExamples: "Metrics definition document, monitoring procedures, measurement records, analysis reports, dashboards, trend reports" },
  { clauseId: "9.2", category: "Performance Evaluation", parentClauseId: "9", title: "Internal audit", description: "The organization shall conduct internal audits at planned intervals to provide information on whether the ISMS conforms to requirements and is effectively implemented and maintained.", guidance: "Establish internal audit program, select competent auditors, define audit criteria, scope, and frequency.", evidenceExamples: "Audit program, audit schedule, audit procedures, auditor competency records" },
  { clauseId: "9.2.1", category: "Performance Evaluation", parentClauseId: "9.2", title: "General", description: "The organization shall plan, establish, implement and maintain an audit programme(s), including the frequency, methods, responsibilities, planning requirements and reporting.", guidance: "Consider importance of processes and results of previous audits when planning.", evidenceExamples: "Annual audit plan, audit methodology document, responsibility matrix for audits" },
  { clauseId: "9.2.2", category: "Performance Evaluation", parentClauseId: "9.2", title: "Internal audit programme", description: "The organization shall define audit criteria and scope for each audit, select auditors to ensure objectivity and impartiality, ensure results are reported to relevant management, and retain documented information as evidence.", guidance: "Document audit findings, nonconformities, and communicate results to appropriate management levels.", evidenceExamples: "Audit reports, nonconformity records, audit evidence files, management communications, corrective action tracking" },
  { clauseId: "9.3", category: "Performance Evaluation", parentClauseId: "9", title: "Management review", description: "Top management shall review the organization's information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness.", guidance: "Conduct regular management reviews (typically annually) with defined inputs and outputs.", evidenceExamples: "Management review schedule, meeting agendas, review input documentation, meeting minutes, action items" },
  { clauseId: "9.3.1", category: "Performance Evaluation", parentClauseId: "9.3", title: "General", description: "Management reviews shall be planned and carried out taking into consideration status of actions from previous reviews, changes in external and internal issues, feedback on performance, nonconformities and corrective actions, monitoring and measurement results, audit results, fulfillment of objectives, and opportunities for improvement.", guidance: "Prepare comprehensive review materials covering all required inputs.", evidenceExamples: "Review agenda template, input document compilation, previous action status report" },
  { clauseId: "9.3.2", category: "Performance Evaluation", parentClauseId: "9.3", title: "Management review inputs", description: "Management review inputs shall include status of actions from previous reviews, changes relevant to ISMS, feedback on security performance including trends in nonconformities and corrective actions, monitoring and measurement results, audit results, fulfillment of objectives, feedback from interested parties, results of risk assessment and status of risk treatment plan, and opportunities for improvement.", guidance: "Systematically collect and present all required input information.", evidenceExamples: "Action tracking log, change summary, performance dashboard, trend analysis, audit summary, objectives status report, stakeholder feedback summary, risk status report" },
  { clauseId: "9.3.3", category: "Performance Evaluation", parentClauseId: "9.3", title: "Management review results", description: "The results of the management review shall include decisions related to continual improvement opportunities and any needs for changes to the information security management system. Documented information shall be retained as evidence of the results.", guidance: "Document decisions, action items with owners and deadlines, and resource allocations.", evidenceExamples: "Management review minutes, action item register, decision records, resource approval records, improvement plans" },
  
  // Clause 10 - Improvement
  { clauseId: "10", category: "Improvement", title: "Improvement", description: "Addresses continual improvement and nonconformity and corrective action requirements.", guidance: "Drive ongoing improvement of the ISMS through systematic processes.", evidenceExamples: "Improvement records, corrective action records, continual improvement program documentation" },
  { clauseId: "10.1", category: "Improvement", parentClauseId: "10", title: "Continual improvement", description: "The organization shall continually improve the suitability, adequacy and effectiveness of the information security management system.", guidance: "Establish mechanisms for identifying and implementing improvements. Use PDCA cycle.", evidenceExamples: "Improvement register, improvement project records, effectiveness measurements, before/after comparisons" },
  { clauseId: "10.2", category: "Improvement", parentClauseId: "10", title: "Nonconformity and corrective action", description: "When a nonconformity occurs, the organization shall react to the nonconformity, evaluate the need for action to eliminate causes, implement any action needed, review the effectiveness of corrective action, and make changes to the ISMS if necessary.", guidance: "Establish corrective action process covering identification, root cause analysis, action implementation, and effectiveness verification.", evidenceExamples: "Nonconformity register, root cause analysis records, corrective action plans, implementation evidence, effectiveness review records, ISMS change records" },
]

// Prepare ISO 27001 controls
  const iso27001Records = iso27001Controls.map((control, index) => ({
    frameworkCode: "iso-27001",
    controlId: control.controlId,
    category: control.category,
    subcategory: control.subcategory,
    title: control.title,
    description: control.description,
    isRequired: true,
    sortOrder: index,
  }))
  
  // Prepare SOC 2 controls
  const soc2Records = soc2Controls.map((control, index) => ({
    frameworkCode: "soc-2",
    controlId: control.controlId,
    category: control.category,
    subcategory: control.subcategory,
    title: control.title,
    description: control.description,
    isRequired: true,
    sortOrder: index,
  }))
  
  // Prepare ISO 27001 ISMS clauses
  const clauseRecords = iso27001Clauses.map((clause, index) => ({
    frameworkCode: "iso-27001",
    clauseId: clause.clauseId,
    parentClauseId: clause.parentClauseId || null,
    title: clause.title,
    description: clause.description,
    guidance: clause.guidance,
    evidenceExamples: clause.evidenceExamples,
    category: clause.category,
    sortOrder: index,
  }))
  
  try {
    // Insert ISO 27001 controls
    console.log(`📋 Inserting ${iso27001Records.length} ISO 27001:2022 Annex A controls...`)
    await db.insert(securityStandardControls).values(iso27001Records).onConflictDoNothing()
    
    // Insert SOC 2 controls
    console.log(`📋 Inserting ${soc2Records.length} SOC 2 Trust Service Criteria...`)
    await db.insert(securityStandardControls).values(soc2Records).onConflictDoNothing()
    
    // Insert ISO 27001 ISMS clauses
    console.log(`📋 Inserting ${clauseRecords.length} ISO 27001:2022 ISMS clauses...`)
    await db.insert(securityStandardClauses).values(clauseRecords).onConflictDoNothing()
    
    console.log("✅ Security controls and clauses seeded successfully!")
    console.log(`   - ISO 27001:2022 Annex A: ${iso27001Records.length} controls`)
    console.log(`   - ISO 27001:2022 ISMS: ${clauseRecords.length} clauses`)
    console.log(`   - SOC 2: ${soc2Records.length} criteria`)
  } catch (error) {
    console.error("❌ Error seeding security controls:", error)
    throw error
  }
}

// Run if called directly
seedSecurityControls()
  .then(() => {
    console.log("Exiting successfully")
    process.exit(0)
  })
  .catch((err) => {
    console.error("Fatal error:", err)
    process.exit(1)
  })

